using System.Runtime.InteropServices;

namespace VsEmacs.Commands
{
    [Guid("9a95f3af-f86a-4aa2-80e6-012bf65dbbc3")]
    public enum EmacsCommandID
    {
        CharLeft = 1,
        CharRight = 2,
        LineUp = 3,
        LineDown = 4,
        LineEnd = 5,
        LineStart = 6,
        DocumentEnd = 7,
        DocumentStart = 8,
        WordPrevious = 9,
        WordNext = 10,
        GoToLine = 11,
        ScrollPageUp = 12,
        ScrollPageDown = 13,
        ScrollLineCenter = 14,
        TopOfWindow = 15,
        BottomOfWindow = 16,
        ScrollLineTop = 17,
        SplitVertical = 18,
        OtherWindow = 19,
        CloseOtherWindow = 20,
        BreakLine = 21,
        BreakLineIndent = 22,
        LineOpen = 23,
        CharTranspose = 24,
        WordTranspose = 25,
        WordUppercase = 29,
        WordLowercase = 30,
        WordCapitalize = 31,
        WordDeleteToEnd = 32,
        WordDeleteToStart = 33,
        DeleteToEndOfLine = 34,
        PasteRotate = 37,
        SetMark = 39,
        PopMark = 40,
        SwapPointAndMark = 41,
        DeleteSelection = 42,
        FileOpen = 43,
        FileSave = 44,
        FileSaveAs = 45,
        FileSaveDirty = 46,
        IncrementalSearch = 47,
        IncrementalSearchBackwards = 48,
        FindReplace = 49,
        Quit = 51,
        UniversalArgument = 52,
        ExtendedCommand = 53,
        QuotedInsert = 58,
        ActivateRegion = 59,
    }
}